// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: rproxyservice.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntryRegistry_RegisterEntry_FullMethodName = "/reverse_proxy.EntryRegistry/RegisterEntry"
	EntryRegistry_UpdateEntry_FullMethodName   = "/reverse_proxy.EntryRegistry/UpdateEntry"
	EntryRegistry_DeleteEntry_FullMethodName   = "/reverse_proxy.EntryRegistry/DeleteEntry"
)

// EntryRegistryClient is the client API for EntryRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntryRegistryClient interface {
	RegisterEntry(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	UpdateEntry(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteEntry(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type entryRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewEntryRegistryClient(cc grpc.ClientConnInterface) EntryRegistryClient {
	return &entryRegistryClient{cc}
}

func (c *entryRegistryClient) RegisterEntry(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, EntryRegistry_RegisterEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryRegistryClient) UpdateEntry(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, EntryRegistry_UpdateEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryRegistryClient) DeleteEntry(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, EntryRegistry_DeleteEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntryRegistryServer is the server API for EntryRegistry service.
// All implementations must embed UnimplementedEntryRegistryServer
// for forward compatibility.
type EntryRegistryServer interface {
	RegisterEntry(context.Context, *RegisterRequest) (*RegisterResponse, error)
	UpdateEntry(context.Context, *UpdateRequest) (*UpdateResponse, error)
	DeleteEntry(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedEntryRegistryServer()
}

// UnimplementedEntryRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntryRegistryServer struct{}

func (UnimplementedEntryRegistryServer) RegisterEntry(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEntry not implemented")
}
func (UnimplementedEntryRegistryServer) UpdateEntry(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEntry not implemented")
}
func (UnimplementedEntryRegistryServer) DeleteEntry(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEntry not implemented")
}
func (UnimplementedEntryRegistryServer) mustEmbedUnimplementedEntryRegistryServer() {}
func (UnimplementedEntryRegistryServer) testEmbeddedByValue()                       {}

// UnsafeEntryRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntryRegistryServer will
// result in compilation errors.
type UnsafeEntryRegistryServer interface {
	mustEmbedUnimplementedEntryRegistryServer()
}

func RegisterEntryRegistryServer(s grpc.ServiceRegistrar, srv EntryRegistryServer) {
	// If the following call panics, it indicates UnimplementedEntryRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntryRegistry_ServiceDesc, srv)
}

func _EntryRegistry_RegisterEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryRegistryServer).RegisterEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryRegistry_RegisterEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryRegistryServer).RegisterEntry(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryRegistry_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryRegistryServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryRegistry_UpdateEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryRegistryServer).UpdateEntry(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryRegistry_DeleteEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryRegistryServer).DeleteEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryRegistry_DeleteEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryRegistryServer).DeleteEntry(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntryRegistry_ServiceDesc is the grpc.ServiceDesc for EntryRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntryRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reverse_proxy.EntryRegistry",
	HandlerType: (*EntryRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEntry",
			Handler:    _EntryRegistry_RegisterEntry_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _EntryRegistry_UpdateEntry_Handler,
		},
		{
			MethodName: "DeleteEntry",
			Handler:    _EntryRegistry_DeleteEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rproxyservice.proto",
}
