// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rproxyservice.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullAddr      string                 `protobuf:"bytes,1,opt,name=fullAddr,proto3" json:"fullAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_rproxyservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rproxyservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_rproxyservice_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetFullAddr() string {
	if x != nil {
		return x.FullAddr
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_rproxyservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rproxyservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_rproxyservice_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldAddr       string                 `protobuf:"bytes,1,opt,name=oldAddr,proto3" json:"oldAddr,omitempty"`
	NewAddr       string                 `protobuf:"bytes,2,opt,name=newAddr,proto3" json:"newAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_rproxyservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rproxyservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_rproxyservice_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetOldAddr() string {
	if x != nil {
		return x.OldAddr
	}
	return ""
}

func (x *UpdateRequest) GetNewAddr() string {
	if x != nil {
		return x.NewAddr
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OldVal        string                 `protobuf:"bytes,2,opt,name=oldVal,proto3" json:"oldVal,omitempty"`
	NewVal        string                 `protobuf:"bytes,3,opt,name=newVal,proto3" json:"newVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_rproxyservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rproxyservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_rproxyservice_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetOldVal() string {
	if x != nil {
		return x.OldVal
	}
	return ""
}

func (x *UpdateResponse) GetNewVal() string {
	if x != nil {
		return x.NewVal
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullAddr      string                 `protobuf:"bytes,1,opt,name=fullAddr,proto3" json:"fullAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_rproxyservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rproxyservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_rproxyservice_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetFullAddr() string {
	if x != nil {
		return x.FullAddr
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_rproxyservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rproxyservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_rproxyservice_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rproxyservice_proto protoreflect.FileDescriptor

const file_rproxyservice_proto_rawDesc = "" +
	"\n" +
	"\x13rproxyservice.proto\x12\rreverse_proxy\"-\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bfullAddr\x18\x01 \x01(\tR\bfullAddr\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\rUpdateRequest\x12\x18\n" +
	"\aoldAddr\x18\x01 \x01(\tR\aoldAddr\x12\x18\n" +
	"\anewAddr\x18\x02 \x01(\tR\anewAddr\"Z\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06oldVal\x18\x02 \x01(\tR\x06oldVal\x12\x16\n" +
	"\x06newVal\x18\x03 \x01(\tR\x06newVal\"+\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bfullAddr\x18\x01 \x01(\tR\bfullAddr\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xff\x01\n" +
	"\rEntryRegistry\x12R\n" +
	"\rRegisterEntry\x12\x1e.reverse_proxy.RegisterRequest\x1a\x1f.reverse_proxy.RegisterResponse\"\x00\x12L\n" +
	"\vUpdateEntry\x12\x1c.reverse_proxy.UpdateRequest\x1a\x1d.reverse_proxy.UpdateResponse\"\x00\x12L\n" +
	"\vDeleteEntry\x12\x1c.reverse_proxy.DeleteRequest\x1a\x1d.reverse_proxy.DeleteResponse\"\x00B\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_rproxyservice_proto_rawDescOnce sync.Once
	file_rproxyservice_proto_rawDescData []byte
)

func file_rproxyservice_proto_rawDescGZIP() []byte {
	file_rproxyservice_proto_rawDescOnce.Do(func() {
		file_rproxyservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rproxyservice_proto_rawDesc), len(file_rproxyservice_proto_rawDesc)))
	})
	return file_rproxyservice_proto_rawDescData
}

var file_rproxyservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rproxyservice_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: reverse_proxy.RegisterRequest
	(*RegisterResponse)(nil), // 1: reverse_proxy.RegisterResponse
	(*UpdateRequest)(nil),    // 2: reverse_proxy.UpdateRequest
	(*UpdateResponse)(nil),   // 3: reverse_proxy.UpdateResponse
	(*DeleteRequest)(nil),    // 4: reverse_proxy.DeleteRequest
	(*DeleteResponse)(nil),   // 5: reverse_proxy.DeleteResponse
}
var file_rproxyservice_proto_depIdxs = []int32{
	0, // 0: reverse_proxy.EntryRegistry.RegisterEntry:input_type -> reverse_proxy.RegisterRequest
	2, // 1: reverse_proxy.EntryRegistry.UpdateEntry:input_type -> reverse_proxy.UpdateRequest
	4, // 2: reverse_proxy.EntryRegistry.DeleteEntry:input_type -> reverse_proxy.DeleteRequest
	1, // 3: reverse_proxy.EntryRegistry.RegisterEntry:output_type -> reverse_proxy.RegisterResponse
	3, // 4: reverse_proxy.EntryRegistry.UpdateEntry:output_type -> reverse_proxy.UpdateResponse
	5, // 5: reverse_proxy.EntryRegistry.DeleteEntry:output_type -> reverse_proxy.DeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rproxyservice_proto_init() }
func file_rproxyservice_proto_init() {
	if File_rproxyservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rproxyservice_proto_rawDesc), len(file_rproxyservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rproxyservice_proto_goTypes,
		DependencyIndexes: file_rproxyservice_proto_depIdxs,
		MessageInfos:      file_rproxyservice_proto_msgTypes,
	}.Build()
	File_rproxyservice_proto = out.File
	file_rproxyservice_proto_goTypes = nil
	file_rproxyservice_proto_depIdxs = nil
}
