// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bootservice.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_bootservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_bootservice_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Neighbors     map[uint64]string      `protobuf:"bytes,2,rep,name=neighbors,proto3" json:"neighbors,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_bootservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_bootservice_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetNeighbors() map[uint64]string {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

var File_bootservice_proto protoreflect.FileDescriptor

const file_bootservice_proto_rawDesc = "" +
	"\n" +
	"\x11bootservice.proto\x12\tbootstrap\"O\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\xb4\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12H\n" +
	"\tneighbors\x18\x02 \x03(\v2*.bootstrap.RegisterResponse.NeighborsEntryR\tneighbors\x1a<\n" +
	"\x0eNeighborsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012Y\n" +
	"\x10BootstrapService\x12E\n" +
	"\bRegister\x12\x1a.bootstrap.RegisterRequest\x1a\x1b.bootstrap.RegisterResponse\"\x00B\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_bootservice_proto_rawDescOnce sync.Once
	file_bootservice_proto_rawDescData []byte
)

func file_bootservice_proto_rawDescGZIP() []byte {
	file_bootservice_proto_rawDescOnce.Do(func() {
		file_bootservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bootservice_proto_rawDesc), len(file_bootservice_proto_rawDesc)))
	})
	return file_bootservice_proto_rawDescData
}

var file_bootservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bootservice_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: bootstrap.RegisterRequest
	(*RegisterResponse)(nil), // 1: bootstrap.RegisterResponse
	nil,                      // 2: bootstrap.RegisterResponse.NeighborsEntry
}
var file_bootservice_proto_depIdxs = []int32{
	2, // 0: bootstrap.RegisterResponse.neighbors:type_name -> bootstrap.RegisterResponse.NeighborsEntry
	0, // 1: bootstrap.BootstrapService.Register:input_type -> bootstrap.RegisterRequest
	1, // 2: bootstrap.BootstrapService.Register:output_type -> bootstrap.RegisterResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bootservice_proto_init() }
func file_bootservice_proto_init() {
	if File_bootservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bootservice_proto_rawDesc), len(file_bootservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootservice_proto_goTypes,
		DependencyIndexes: file_bootservice_proto_depIdxs,
		MessageInfos:      file_bootservice_proto_msgTypes,
	}.Build()
	File_bootservice_proto = out.File
	file_bootservice_proto_goTypes = nil
	file_bootservice_proto_depIdxs = nil
}
